import { prisma } from "@/lib/prisma";
import { ProxmoxFabricClient } from "@/integrations/proxmox/fabric-client";
type A={externalId:string;assetType:"STORAGE"|"NETWORK";name:string;nodeName?:string;parentExternalId?:string;status:string;diskUsedBytes?:bigint;diskTotalBytes?:bigint;metadata:Record<string,unknown>};
const j=(v:Record<string,unknown>)=>JSON.parse(JSON.stringify(v));
async function persist(org:string,intg:string,assets:A[]){
 let createdCount=0,updatedCount=0,unchangedCount=0;const ids=assets.map(a=>a.externalId);
 for(const a of assets){const e=await prisma.infrastructureAsset.findUnique({where:{organizationId_provider_externalId:{organizationId:org,provider:"PROXMOX",externalId:a.externalId}}});const before=e?JSON.stringify([e.name,e.status,e.nodeName,e.diskUsedBytes?.toString(),e.diskTotalBytes?.toString()]):"";const after=JSON.stringify([a.name,a.status,a.nodeName,a.diskUsedBytes?.toString(),a.diskTotalBytes?.toString()]);const changed=!e||before!==after;const now=new Date();
 await prisma.infrastructureAsset.upsert({where:{organizationId_provider_externalId:{organizationId:org,provider:"PROXMOX",externalId:a.externalId}},update:{integrationId:intg,assetType:a.assetType,name:a.name,nodeName:a.nodeName,parentExternalId:a.parentExternalId,status:a.status,diskUsedBytes:a.diskUsedBytes,diskTotalBytes:a.diskTotalBytes,metadata:j(a.metadata),active:true,lastSeenAt:now,lastChangedAt:changed?now:e?.lastChangedAt},create:{organizationId:org,integrationId:intg,provider:"PROXMOX",externalId:a.externalId,assetType:a.assetType,name:a.name,nodeName:a.nodeName,parentExternalId:a.parentExternalId,status:a.status,diskUsedBytes:a.diskUsedBytes,diskTotalBytes:a.diskTotalBytes,metadata:j(a.metadata),active:true,lastSeenAt:now,lastChangedAt:now}});
 if(!e)createdCount++;else if(changed)updatedCount++;else unchangedCount++}
 const missing=await prisma.infrastructureAsset.updateMany({where:{organizationId:org,provider:"PROXMOX",assetType:{in:["STORAGE","NETWORK"]},active:true,externalId:{notIn:ids}},data:{active:false,status:"MISSING",lastChangedAt:new Date()}});
 const verifiedCount=await prisma.infrastructureAsset.count({where:{organizationId:org,provider:"PROXMOX",assetType:{in:["STORAGE","NETWORK"]},externalId:{in:ids}}});
 if(verifiedCount!==assets.length)throw new Error(`Fabric Discovery: ${verifiedCount}/${assets.length} ativos confirmados.`);
 return{createdCount,updatedCount,unchangedCount,offlineCount:missing.count,verifiedCount}}
export async function discoverProxmoxFabric(p:{organizationId:string;integrationId:string;userId:string}){
 const run=await prisma.discoveryRun.create({data:{organizationId:p.organizationId,integrationId:p.integrationId,userId:p.userId,provider:"PROXMOX",scope:"STORAGE_NETWORK",status:"RUNNING",endpoint:process.env.PROXMOX_BASE_URL}});const started=Date.now();const c=new ProxmoxFabricClient();
 try{const[nodes,storages]=await Promise.all([c.getNodes(),c.getStorage()]);const assets:A[]=[];
 for(const s of storages){const name=s.storage??s.id;assets.push({externalId:`storage/${s.node??"cluster"}/${name}`,assetType:"STORAGE",name,nodeName:s.node,parentExternalId:s.node?`node/${s.node}`:undefined,status:(s.status??"AVAILABLE").toUpperCase(),diskUsedBytes:typeof s.disk==="number"?BigInt(Math.trunc(s.disk)):undefined,diskTotalBytes:typeof s.maxdisk==="number"?BigInt(Math.trunc(s.maxdisk)):undefined,metadata:{storageType:s.type,shared:s.shared===1,content:s.content}})}
 let networkCount=0;for(const n of nodes){for(const i of await c.getNetwork(n.node)){if(!["bridge","bond","eth","vlan","OVSBridge","OVSBond","OVSPort","OVSIntPort"].includes(i.type??""))continue;networkCount++;assets.push({externalId:`network/${n.node}/${i.iface}`,assetType:"NETWORK",name:i.iface,nodeName:n.node,parentExternalId:`node/${n.node}`,status:i.active===1?"ONLINE":"OFFLINE",metadata:{interfaceType:i.type,address:i.address,cidr:i.cidr,netmask:i.netmask,gateway:i.gateway,autostart:i.autostart===1,bridgePorts:i.bridge_ports,vlanAware:i.bridge_vlan_aware===1,bondSlaves:i.bond_slaves,bondMode:i.bond_mode,comments:i.comments}})}}
 const saved=await persist(p.organizationId,p.integrationId,assets);const durationMs=Date.now()-started;await prisma.discoveryRun.update({where:{id:run.id},data:{status:"COMPLETED",completedAt:new Date(),durationMs,discovered:assets.length,createdCount:saved.createdCount,updatedCount:saved.updatedCount,unchangedCount:saved.unchangedCount,offlineCount:saved.offlineCount,metadata:{storageCount:storages.length,networkCount,verifiedCount:saved.verifiedCount}}});return{runId:run.id,storageCount:storages.length,networkCount,durationMs,...saved}
 }catch(error){const message=error instanceof Error?error.message:"Erro desconhecido.";await prisma.discoveryRun.update({where:{id:run.id},data:{status:"FAILED",completedAt:new Date(),durationMs:Date.now()-started,errorMessage:message}});throw error}}
