import type { ReactNode } from "react";
import { PortalShell } from "@/components/portal/portal-shell";
import { requireOrganization } from "@/lib/authz";
import "./portal.css";
import "./enterprise.css";
import "./data-layer.css";
import "./integration.css";
import "./integration-hotfix.css";
import "./discovery.css";
import "./discovery-ui.css";
import "./virtual-discovery.css";
import "./fabric-discovery.css";
import "./multi-proxmox.css";
import "./registry-consolidation.css";
import "./impact-intelligence.css";
import "./incident-correlation.css";
import "./incident-lifecycle.css";
import "./alerting-escalation.css";
import "./notification-connectors.css";
import "./notificacoes/governance.css";
import "./notificacoes/automation.css";
import "./notification-observability.css";
import "./observabilidade/noc-health.css";
import "./observabilidade/slo-trend.css";
import "./observabilidade/slo-automation.css";
import "./observabilidade/slo-reporting.css";
import "./observabilidade/retention-governance.css";
import "./executive-cockpit.css";
import "./cockpit/site-health.css";
import "./discovery/discovery-automation.css";
import "./incidentes/incident-reconciliation.css";
import "./incidentes/reconciliation/discovery-lifecycle.css";
import "./incidentes/reliability/incident-reliability.css";
import "./hoiwork-typography.css";
import "./incidentes/sla/incident-sla.css";
import "./incidentes/sla/delivery/sla-delivery-observability.css";
import "./incidentes/[id]/incident-command-center.css";
import "./incidentes/[id]/remediation-intelligence.css";
import "./incidentes/[id]/remediation-plan.css";
import "./incidentes/[id]/remediation-executor.css";
import "./incidentes/[id]/remediation-verification.css";
import "./incidentes/[id]/remediation-governance.css";
import "./incidentes/[id]/remediation-authorization.css";
import "./incidentes/[id]/remediation-approval-renewal.css";
import "./incidentes/[id]/remediation-real-executor.css";
import "./incidentes/[id]/post-remediation-assurance.css";
import "./incidentes/[id]/post-remediation-stability.css";
import "./incidentes/[id]/post-remediation-closure.css";
import "./incidentes/[id]/post-closure-regression.css";
import "./cockpit/control-plane-health.css";
import "./cockpit/control-plane-root-cause.css";
import "./cockpit/control-plane-reliability.css";

export default async function PortalLayout({ children }: { children: ReactNode }) {
  await requireOrganization();
  return <PortalShell>{children}</PortalShell>;
}
