services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: hoiwork
      POSTGRES_USER: hoiwork
      POSTGRES_PASSWORD: nC!w*72_Bwb@77.94
    ports:
      - "5432:5432"
    volumes:
      - hoiwork_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hoiwork -d hoiwork"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  hoiwork_postgres_data:
