export const manualSections = [
  {
    id: "primeiros-passos",
    title: "Primeiros passos",
    level: "Básico",
    intro: "O Portal Enterprise reúne infraestrutura, atendimento e continuidade da organização vinculada ao seu acesso. Comece pelo Dashboard e siga o fluxo: conectar → descobrir → conferir → acompanhar → tratar.",
    steps: [
      "Entre com o usuário autorizado para o cliente. Se não houver organização vinculada ou acesso ativo, solicite ao administrador a revisão do vínculo.",
      "No Dashboard, conheça os indicadores. Depois abra Integrações para conferir a origem dos dados e a última sincronização antes de interpretar a saúde do ambiente.",
      "Use o menu lateral para as áreas principais e os atalhos deste manual para Observabilidade, Cockpit e Incidentes, que também possuem páginas próprias.",
      "Confirme a organização no cabeçalho e, em cada integração, confira o modo DEMO/LIVE e a data da última coleta antes de interpretar os dados.",
    ],
    note: "A Ajuda é material de consulta. Abrir seus links não executa Discovery, sincronização, remediação ou automações.",
    links: [{ href: "/portal", label: "Abrir Dashboard" }],
  },
  {
    id: "onboarding",
    title: "Novo cliente e onboarding",
    level: "Básico",
    intro: "Prepare o acesso e o contexto do cliente antes de cadastrar a infraestrutura. Organização, usuário e vínculo de acesso são diferentes de uma instância Proxmox.",
    steps: [
      "Reúna nome do cliente, responsáveis, contatos, sites, escopo contratado e ambientes que serão acompanhados.",
      "Solicite ao administrador o provisionamento da organização e dos usuários, com os vínculos e permissões necessários. O portal atual não oferece uma tela administrativa completa de cadastro de novos clientes.",
      "O administrador pode consultar usuários vinculados e alterar seus papéis em Organização e acessos. A alteração do próprio papel é bloqueada e cada mudança é auditada.",
      "Para um novo usuário, o ADMIN cria um convite em Organização e acessos e compartilha o link por um canal seguro. O link vence em 24 horas, só funciona uma vez e permite ao convidado definir sua própria senha. E-mails já cadastrados precisam de um fluxo de vínculo separado.",
      "Em Convites recentes, acompanhe os estados pendente, aceito, expirado e revogado. Revogue um convite pendente se o link tiver sido compartilhado por engano; para gerar outro link após a revogação, crie um novo convite.",
      "O ADMIN pode suspender e reativar o vínculo de outro usuário em Organização e acessos. Uma suspensão impede novos logins nesse vínculo e bloqueia sessões existentes nas rotas da organização. O último ADMIN ativo permanece protegido.",
      "Consulte Histórico de acessos, na mesma página, para ver as 50 alterações mais recentes em convites, papéis e suspensões, com responsável e destinatário.",
      "Valide o primeiro login com o usuário do cliente e confirme com o administrador que ele está vinculado à organização correta.",
      "Cadastre as instâncias Proxmox do cliente no Integration Registry, teste cada conexão e execute o Discovery da instância desejada.",
      "Confira recursos descobertos, inventário, contratos e planos de Backup/DR. Combine responsáveis por chamados, incidentes e revisão diária do Cockpit.",
    ],
    note: "Não use o cadastro de Proxmox como substituto do cadastro de cliente. Cada instância pertence à organização do usuário autenticado.",
    links: [{ href: "/portal/organizacao", label: "Organização e acessos (ADMIN)" }, { href: "/portal/integracoes/proxmox", label: "Cadastrar Proxmox" }, { href: "/portal/contratos", label: "Consultar contratos" }],
  },
  {
    id: "proxmox-local",
    title: "Proxmox local",
    level: "Operação",
    intro: "Use o Integration Registry para adicionar instâncias com endpoint e credenciais próprios. O conector legado configurado no servidor continua existindo e deve ser distinguido das instâncias adicionais.",
    steps: [
      "Abra Multi-Proxmox e localize “Adicionar novo Proxmox”. Informe Nome e Site com identificação clara, por exemplo, Matriz / Produção.",
      "Preencha URL com o endereço HTTPS acessível pelo servidor HOIWORK, incluindo a porta quando necessária; por exemplo, https://pve.exemplo.interno:8006.",
      "Informe Token ID e Token Secret fornecidos pelo administrador Proxmox. Use credenciais com permissões adequadas à coleta e nunca inclua segredos em chamados ou capturas de tela.",
      "Revise “Permitir certificado autoassinado” conforme a configuração do ambiente. Prefira certificados validados e trate qualquer exceção com o responsável pela infraestrutura.",
      "Salve a instância, use “Testar conexão” e só então execute seu Discovery. Confira status, horário e resultado, sem confundir conexão bem-sucedida com coleta concluída.",
    ],
    note: "“Remover” exclui o cadastro e as credenciais do Registry e pede confirmação. Não utilize essa ação como tentativa inicial de corrigir uma falha de conexão.",
    links: [{ href: "/portal/integracoes/proxmox", label: "Abrir Multi-Proxmox / Registry" }],
  },
  {
    id: "proxmox-remoto",
    title: "Proxmox remoto e múltiplos sites",
    level: "Operação",
    intro: "O cadastro é o mesmo do Proxmox local. A diferença é o caminho de rede entre o servidor HOIWORK e o endpoint do ambiente remoto.",
    steps: [
      "Combine com a equipe de rede uma conexão controlada, como VPN ou rede privada, e valide DNS, rota e firewall a partir do servidor HOIWORK. Acesso pelo seu navegador, sozinho, não comprova essa conectividade.",
      "Cadastre uma instância por ambiente, com Nome e Site distintos, URL remota correta e token específico.",
      "Teste a conexão de cada instância separadamente. Em timeout, confira conectividade; em falha de autenticação, revise token e permissões; em erro TLS, revise certificado e hostname.",
      "Execute Discovery e confira a identificação do site na topologia. Instâncias distintas podem ter nomes de nodes ou VMIDs iguais; mantenha a origem de cada recurso identificada.",
    ],
    note: "Adicionar um endpoint não configura VPN, DNS ou firewall. Essas dependências precisam estar prontas na infraestrutura.",
    links: [{ href: "/portal/integracoes/proxmox", label: "Abrir instâncias" }, { href: "/portal/discovery", label: "Consultar topologia" }],
  },
  {
    id: "integracoes",
    title: "Integrações e Digital Twin",
    level: "Operação",
    intro: "Integrações mostra diagnóstico do conector Proxmox, recursos sincronizados e Digital Twin: uma representação operacional dos recursos coletados, com estado e métricas disponíveis.",
    steps: [
      "Confira Modo, Endpoint, TLS e Última sincronização no topo da página para saber qual fonte está sendo exibida.",
      "Use “Testar conexão” para diagnosticar acesso ao conector. Para atualizar seus recursos, use “Sincronizar Proxmox” e aguarde o resultado.",
      "Revise as últimas sincronizações: status, quantidade de recursos e mensagem de erro. Uma sincronização antiga pode explicar dados defasados.",
      "Explore o Digital Twin e compare os estados dos recursos com os dados de Discovery. A página do conector legado e o Registry têm escopos distintos; não presuma que uma única tela reúne todas as instâncias.",
      "Leia os componentes do Risk Score junto do nível de risco. O indicador considera recursos, integração, backup, DR e chamados críticos; não substitui a investigação dos sinais individuais.",
    ],
    note: "Métricas ausentes ou antigas não comprovam saúde. Verifique a fonte e a última coleta antes de concluir que o ambiente está normal.",
    links: [{ href: "/portal/integracoes", label: "Abrir Integrações / Digital Twin" }, { href: "/portal/integracoes/proxmox", label: "Abrir Registry" }],
  },
  {
    id: "discovery",
    title: "Discovery",
    level: "Operação",
    intro: "Discovery identifica a infraestrutura e mantém evidências das coletas. A tela reúne nodes, infraestrutura virtual, fabric e topologia de múltiplos sites.",
    steps: [
      "Valide a integração antes de descobrir recursos. Para instâncias adicionais, inicie pelo Discovery da instância no Registry.",
      "Na página Discovery, utilize o controle correspondente ao escopo desejado. “Descobrir Nodes Reais” coleta nodes; os painéis de infraestrutura virtual e fabric têm controles próprios.",
      "Aguarde a conclusão e confira recursos confirmados, novos, alterados e sem mudanças. Registre mensagens de falha e o horário da execução.",
      "Consulte histórico e logs, depois revise nodes, máquinas virtuais, containers, storage, redes e relações que estiverem disponíveis nos painéis.",
      "Investigue estados offline ou ausentes considerando o último sucesso da coleta. Uma indisponibilidade do conector pode afetar a visão dos recursos.",
    ],
    note: "Discovery atualiza registros e histórico no portal. Sua execução é uma ação operacional, diferente de apenas consultar esta página de Ajuda.",
    links: [{ href: "/portal/discovery", label: "Abrir Discovery" }, { href: "/portal/integracoes/proxmox", label: "Escolher instância" }],
  },
  {
    id: "inventario",
    title: "Inventário",
    level: "Operação",
    intro: "O Inventário corporativo reúne recursos Proxmox descobertos e ativos cadastrados na organização, com as fontes apresentadas separadamente.",
    steps: [
      "Pesquise por nome, nó, VMID ou IP. Para ativos cadastrados manualmente, a pesquisa também considera fabricante, modelo e número de série.",
      "Filtre por nós, VMs, contêineres, storages, redes ou tipos de ativos cadastrados, como servidores, firewalls e switches.",
      "Revise clusters e seus endpoints, nós e recursos associados. Confira a última sincronização de cada endpoint antes de interpretar o estado dos recursos.",
      "Confira ativos cadastrados na seção separada. Se não houver resultados, limpe a pesquisa, selecione todos os tipos e verifique a coleta e a organização ativa.",
    ],
    note: "Campos com traço indicam ausência de informação; não significam que o equipamento esteja indisponível.",
    links: [{ href: "/portal/inventario", label: "Pesquisar inventário" }],
  },
  {
    id: "observabilidade",
    title: "Observabilidade e SLO",
    level: "Avançado",
    intro: "Observabilidade reúne saúde do NOC, entregas de notificações, latência, conectores e SLO. SLO é o objetivo de nível de serviço usado para acompanhar a qualidade operacional.",
    steps: [
      "Comece pelo estado das entregas e dos conectores. Diferencie entregas LIVE de demonstração e confira a janela de dados apresentada.",
      "Leia o painel NOC e as tendências de SLO para distinguir falhas pontuais de degradação recorrente. Falta de amostras não equivale a cumprimento do objetivo.",
      "Use os relatórios e snapshots existentes como evidência. Capturar um novo snapshot é uma ação explícita; confirme o contexto antes de executá-la.",
      "Quando uma notificação falhar, consulte conectores e histórico em Notificações e correlacione o horário com o incidente ou evento de origem.",
      "Deixe alterações de retenção, agendamento e governança para os responsáveis. Consulte o capítulo de Governança antes de operar esses controles.",
    ],
    note: "Um problema de entrega de notificação e um problema de infraestrutura são sinais diferentes. Investigue ambos sem assumir que um prova o outro.",
    links: [{ href: "/portal/observabilidade", label: "Abrir Observabilidade" }, { href: "/portal/notificacoes", label: "Consultar Notificações" }],
  },
  {
    id: "cockpit",
    title: "Cockpit",
    level: "Avançado",
    intro: "O Cockpit consolida saúde, risco, incidentes e confiabilidade para priorizar a operação. Use-o como ponto de partida para investigar as áreas detalhadas.",
    steps: [
      "Revise a visão executiva no início do turno e identifique os sinais que exigem atenção.",
      "Compare saúde por site, incidentes e confiabilidade do plano de controle. Observe as datas e as evidências apresentadas.",
      "Siga para Discovery ao investigar recursos, Observabilidade ao investigar entregas/SLO e Incidentes ao acompanhar tratamento.",
      "Depois de uma intervenção, confira se as coletas e os indicadores foram atualizados antes de considerar o problema resolvido.",
    ],
    note: "A visão consolidada orienta a prioridade; a confirmação de causa e recuperação depende dos detalhes e evidências de cada área.",
    links: [{ href: "/portal/cockpit", label: "Abrir Cockpit" }, { href: "/portal/incidentes", label: "Investigar incidentes" }],
  },
  {
    id: "chamados-incidentes",
    title: "Chamados e incidentes",
    level: "Operação",
    intro: "Chamados registram solicitações de atendimento. Incidentes organizam a investigação e o tratamento de eventos operacionais; as duas áreas têm fluxos próprios.",
    steps: [
      "Em Chamados, use “Abrir chamado” e descreva o problema, impacto, cliente/site, recurso afetado, início da falha e evidências sem credenciais.",
      "Acompanhe solicitações pelos filtros Abertos, Em andamento, Resolvidos e Fechados.",
      "Em Incidentes, abra o item correspondente para revisar contexto, evidências e ciclo de tratamento. Consulte também SLA e reconciliação quando necessário.",
      "Antes de uma remediação, revise plano, autorização e escopo nos controles disponíveis. Não confunda recomendação, aprovação, execução e verificação de resultado.",
      "Registre a recuperação e acompanhe estabilidade ou recorrência antes do encerramento conforme o procedimento da equipe.",
    ],
    note: "Não cole tokens, senhas ou segredos de integração em descrições, logs compartilhados ou anexos.",
    links: [{ href: "/portal/chamados", label: "Abrir Chamados" }, { href: "/portal/incidentes", label: "Abrir Incidentes" }, { href: "/portal/incidentes/sla", label: "Consultar SLA" }],
  },
  {
    id: "backup-dr",
    title: "Backup e Disaster Recovery",
    level: "Avançado",
    intro: "Backup Center apresenta jobs e retenção. Disaster Recovery apresenta o plano de continuidade, sites, replicação e objetivos de recuperação.",
    steps: [
      "Em Backup Center, confira status, última execução, retenção e progresso de cada job. Investigue jobs sem execução ou com dados antigos.",
      "Em Disaster Recovery, confira origem, site de recuperação, estado da replicação e última sincronização.",
      "Interprete RPO como objetivo de perda máxima de dados em tempo e RTO como objetivo de tempo para recuperação. Os valores exibidos são objetivos do plano, não garantia de resultado de um teste.",
      "Combine com a equipe responsável testes de restauração e continuidade, com evidências. As páginas atuais são de consulta e não oferecem execução de restauração ou failover.",
    ],
    note: "Sem job ou plano cadastrado, solicite a revisão dos registros ao responsável. Um indicador de proteção não substitui um teste de restauração.",
    links: [{ href: "/portal/backup", label: "Abrir Backup Center" }, { href: "/portal/disaster-recovery", label: "Consultar plano de DR" }],
  },
  {
    id: "governanca",
    title: "Governança e automações",
    level: "Avançado",
    intro: "Automações têm configuração, intervalo, histórico e controles de execução. Revise esses elementos antes de qualquer mudança operacional.",
    steps: [
      "Consulte os painéis de automação de Discovery, Notificações e Observabilidade para entender qual rotina está sendo acompanhada.",
      "Em Autonomous Governance, diferencie DRY_RUN, que avalia sem aplicar as ações de COMMIT, de COMMIT, que pode efetivar mudanças.",
      "Mantenha Autonomous Governance COMMIT desabilitado (commitEnabled=false). Este manual não autoriza sua ativação.",
      "Leia o histórico de execução, modo, status, duração, erros e motivos de bloqueio. Uma execução concluída pode conter ações bloqueadas; isso não comprova que mudanças foram aplicadas.",
      "Solicite revisão técnica antes de alterar intervalo, retenção ou permissões. Concorrência, limites e resultados precisam ser avaliados pelos responsáveis pela operação.",
    ],
    note: "A inclusão desta Ajuda não modifica configurações de governança, não agenda execuções e não habilita COMMIT.",
    links: [{ href: "/portal/observabilidade", label: "Consultar governança" }, { href: "/portal/discovery", label: "Consultar automação de Discovery" }, { href: "/portal/notificacoes", label: "Consultar automação de notificações" }],
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting e rotina de operação",
    level: "Referência",
    intro: "Investigue na ordem: acesso → organização → conectividade → credenciais → coleta → dados → indicadores. Registre a mensagem exata e o horário antes de repetir uma ação.",
    steps: [
      "Login redirecionado ou acesso negado: entre novamente; se persistir, peça ao administrador para revisar vínculo, organização ativa e permissões.",
      "Timeout no Proxmox: confira URL, porta, DNS, rota/VPN e firewall a partir do servidor HOIWORK. Erro TLS: confira certificado e nome do endpoint. Erro de autenticação: revise Token ID, validade e permissões com o administrador.",
      "Discovery vazio ou defasado: confirme a instância, o escopo e a última coleta bem-sucedida; leia os logs antes de repetir. Não remova a integração para tentar corrigir o problema.",
      "Inventário sem resultados: limpe filtros, confirme a última coleta Proxmox e confira os ativos cadastrados. Métrica ausente ou SLO sem amostras: valide janela, coleta e origem dos dados.",
      "Notificação não recebida: confira conector, resultado de entrega e evidências em Observabilidade e Notificações. Correlacione com o evento original.",
      "Automação bloqueada ou não executada: consulte modo, histórico, intervalo e motivos registrados. Não habilite COMMIT para contornar o bloqueio.",
      "Sem solução: abra chamado com site/instância, recurso, horário, ação realizada, resultado esperado e mensagem de erro, removendo segredos.",
      "Na rotina diária, revise Cockpit, falhas de coleta, chamados/incidentes e Backup/DR. Periodicamente, revise acesso, credenciais, objetivos de serviço e evidências de recuperação com os responsáveis.",
    ],
    note: "Uma intervenção só deve ser considerada concluída após conferir novas evidências de coleta e recuperação.",
    links: [{ href: "/portal/chamados", label: "Solicitar atendimento" }, { href: "/portal/cockpit", label: "Iniciar revisão diária" }],
  },
] as const;

export type ManualSectionId = (typeof manualSections)[number]["id"];
