import type { DiscoveredResource, IntegrationHealth, IntegrationProvider } from "@/integrations/core/types";
type R={id:string;type:string;node?:string;vmid?:number;name?:string;status?:string;cpu?:number;maxcpu?:number;mem?:number;maxmem?:number;disk?:number;maxdisk?:number;uptime?:number;template?:number;tags?:string};
type E<T>={data:T};
export type ProxmoxConfig={baseUrl:string;tokenId:string;tokenSecret:string};
function req(v:string|undefined,n:string){if(!v?.trim()) throw new Error(`${n} não configurada.`); return v.trim();}
export function getProxmoxConfigFromEnv():ProxmoxConfig{return{baseUrl:req(process.env.PROXMOX_BASE_URL,"PROXMOX_BASE_URL").replace(/\/$/,""),tokenId:req(process.env.PROXMOX_TOKEN_ID,"PROXMOX_TOKEN_ID"),tokenSecret:req(process.env.PROXMOX_TOKEN_SECRET,"PROXMOX_TOKEN_SECRET")};}
export class ProxmoxConnector implements IntegrationProvider{
 constructor(private readonly config:ProxmoxConfig){}
 private async request<T>(path:string):Promise<T>{const response=await fetch(`${this.config.baseUrl}/api2/json${path}`,{headers:{Authorization:`PVEAPIToken=${this.config.tokenId}=${this.config.tokenSecret}`,Accept:"application/json"},cache:"no-store",signal:AbortSignal.timeout(15000)}); if(!response.ok) throw new Error(`Proxmox API ${response.status}: ${response.statusText}`); const payload=await response.json() as E<T>; return payload.data;}
 async health():Promise<IntegrationHealth>{try{await this.request<Array<{node:string;status:string}>>("/nodes");return{ok:true,message:"Conexão com Proxmox VE estabelecida.",checkedAt:new Date()};}catch(e){return{ok:false,message:e instanceof Error?e.message:"Falha desconhecida.",checkedAt:new Date()};}}
 async discover():Promise<DiscoveredResource[]>{const all=[...(await this.request<R[]>("/cluster/resources?type=node")),...(await this.request<R[]>("/cluster/resources?type=vm")),...(await this.request<R[]>("/cluster/resources?type=storage"))]; return all.filter(i=>i.template!==1).map(i=>({externalId:i.id,kind:i.type==="qemu"?"VM":i.type==="lxc"?"LXC":i.type.toUpperCase(),name:i.name||i.node||i.id,status:(i.status||"unknown").toUpperCase(),node:i.node,cpuPercent:typeof i.cpu==="number"?Math.round(i.cpu*10000)/100:undefined,memoryUsedBytes:typeof i.mem==="number"?BigInt(Math.trunc(i.mem)):undefined,memoryTotalBytes:typeof i.maxmem==="number"?BigInt(Math.trunc(i.maxmem)):undefined,diskUsedBytes:typeof i.disk==="number"?BigInt(Math.trunc(i.disk)):undefined,diskTotalBytes:typeof i.maxdisk==="number"?BigInt(Math.trunc(i.maxdisk)):undefined,uptimeSeconds:typeof i.uptime==="number"?BigInt(Math.trunc(i.uptime)):undefined,metadata:{vmid:i.vmid,maxcpu:i.maxcpu,tags:i.tags}}));}
}
